services:
  - type: web
    name: expense-tracker-backend
    env: node
    plan: free
    region: oregon
    buildCommand: npm ci --only=production
    startCommand: node server.js
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production