services:
  - type: web
    name: expense-tracker-backend
    env: node
    plan: free
    region: oregon
    buildCommand: npm install --production
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production